# This is a basic workflow to help you get started with Actions

name: Copy file to aws ec2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        password: ${{secrets.ssh_password}}
        source: "generate_csv.py,model_predict.py,process_data.py,run_prog.sh,upload_ml_prices.py"
        username: "ubuntu"
        host: "ec2-54-157-45-155.compute-1.amazonaws.com"
        target: "/home/ubuntu"
